//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartyJuice.PJManagementSystem.PJServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Warehouse", Namespace="http://schemas.datacontract.org/2004/07/PartyJuice.DbEntity")]
    [System.SerializableAttribute()]
    public partial class Warehouse : PartyJuice.PJManagementSystem.PJServiceReference.NameEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PartyJuice.PJManagementSystem.PJServiceReference.WarehouseElement[] DrinkElementsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PartyJuice.PJManagementSystem.PJServiceReference.WarehouseElement[] DrinkElements {
            get {
                return this.DrinkElementsField;
            }
            set {
                if ((object.ReferenceEquals(this.DrinkElementsField, value) != true)) {
                    this.DrinkElementsField = value;
                    this.RaisePropertyChanged("DrinkElements");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IdEntity", Namespace="http://schemas.datacontract.org/2004/07/PartyJuice.DbEntity")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PartyJuice.PJManagementSystem.PJServiceReference.WarehouseElement))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PartyJuice.PJManagementSystem.PJServiceReference.Price))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PartyJuice.PJManagementSystem.PJServiceReference.PhoneNumber))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PartyJuice.PJManagementSystem.PJServiceReference.Client))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PartyJuice.PJManagementSystem.PJServiceReference.DiscountCard))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PartyJuice.PJManagementSystem.PJServiceReference.SaleOrder))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PartyJuice.PJManagementSystem.PJServiceReference.User))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PartyJuice.PJManagementSystem.PJServiceReference.PurchaseInvoice))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PartyJuice.PJManagementSystem.PJServiceReference.NameEntity))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PartyJuice.PJManagementSystem.PJServiceReference.Warehouse))]
    public partial class IdEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsDeletedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDeleted {
            get {
                return this.IsDeletedField;
            }
            set {
                if ((this.IsDeletedField.Equals(value) != true)) {
                    this.IsDeletedField = value;
                    this.RaisePropertyChanged("IsDeleted");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WarehouseElement", Namespace="http://schemas.datacontract.org/2004/07/PartyJuice.DbEntity")]
    [System.SerializableAttribute()]
    public partial class WarehouseElement : PartyJuice.PJManagementSystem.PJServiceReference.IdEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PartyJuice.PJManagementSystem.PJServiceReference.Drink DrinkField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Count {
            get {
                return this.CountField;
            }
            set {
                if ((this.CountField.Equals(value) != true)) {
                    this.CountField = value;
                    this.RaisePropertyChanged("Count");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PartyJuice.PJManagementSystem.PJServiceReference.Drink Drink {
            get {
                return this.DrinkField;
            }
            set {
                if ((object.ReferenceEquals(this.DrinkField, value) != true)) {
                    this.DrinkField = value;
                    this.RaisePropertyChanged("Drink");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Price", Namespace="http://schemas.datacontract.org/2004/07/PartyJuice.DbEntity")]
    [System.SerializableAttribute()]
    public partial class Price : PartyJuice.PJManagementSystem.PJServiceReference.IdEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double DrinkPriceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double DrinkPrice {
            get {
                return this.DrinkPriceField;
            }
            set {
                if ((this.DrinkPriceField.Equals(value) != true)) {
                    this.DrinkPriceField = value;
                    this.RaisePropertyChanged("DrinkPrice");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PhoneNumber", Namespace="http://schemas.datacontract.org/2004/07/PartyJuice.DbEntity")]
    [System.SerializableAttribute()]
    public partial class PhoneNumber : PartyJuice.PJManagementSystem.PJServiceReference.IdEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PartyJuice.PJManagementSystem.PJServiceReference.PhoneNumberKind KindField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PartyJuice.PJManagementSystem.PJServiceReference.PhoneNumberKind Kind {
            get {
                return this.KindField;
            }
            set {
                if ((this.KindField.Equals(value) != true)) {
                    this.KindField = value;
                    this.RaisePropertyChanged("Kind");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Number {
            get {
                return this.NumberField;
            }
            set {
                if ((object.ReferenceEquals(this.NumberField, value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Client", Namespace="http://schemas.datacontract.org/2004/07/PartyJuice.DbEntity")]
    [System.SerializableAttribute()]
    public partial class Client : PartyJuice.PJManagementSystem.PJServiceReference.IdEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime BirthDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PartyJuice.PJManagementSystem.PJServiceReference.DiscountCard CardField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PartyJuice.PJManagementSystem.PJServiceReference.PhoneNumber[] ClientsPhoneNumbersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FatherNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PartyJuice.PJManagementSystem.PJServiceReference.Sex SexField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime BirthDate {
            get {
                return this.BirthDateField;
            }
            set {
                if ((this.BirthDateField.Equals(value) != true)) {
                    this.BirthDateField = value;
                    this.RaisePropertyChanged("BirthDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PartyJuice.PJManagementSystem.PJServiceReference.DiscountCard Card {
            get {
                return this.CardField;
            }
            set {
                if ((object.ReferenceEquals(this.CardField, value) != true)) {
                    this.CardField = value;
                    this.RaisePropertyChanged("Card");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PartyJuice.PJManagementSystem.PJServiceReference.PhoneNumber[] ClientsPhoneNumbers {
            get {
                return this.ClientsPhoneNumbersField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientsPhoneNumbersField, value) != true)) {
                    this.ClientsPhoneNumbersField = value;
                    this.RaisePropertyChanged("ClientsPhoneNumbers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FatherName {
            get {
                return this.FatherNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FatherNameField, value) != true)) {
                    this.FatherNameField = value;
                    this.RaisePropertyChanged("FatherName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PartyJuice.PJManagementSystem.PJServiceReference.Sex Sex {
            get {
                return this.SexField;
            }
            set {
                if ((this.SexField.Equals(value) != true)) {
                    this.SexField = value;
                    this.RaisePropertyChanged("Sex");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DiscountCard", Namespace="http://schemas.datacontract.org/2004/07/PartyJuice.DbEntity")]
    [System.SerializableAttribute()]
    public partial class DiscountCard : PartyJuice.PJManagementSystem.PJServiceReference.IdEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DiscountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Discount {
            get {
                return this.DiscountField;
            }
            set {
                if ((this.DiscountField.Equals(value) != true)) {
                    this.DiscountField = value;
                    this.RaisePropertyChanged("Discount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Number {
            get {
                return this.NumberField;
            }
            set {
                if ((this.NumberField.Equals(value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SaleOrder", Namespace="http://schemas.datacontract.org/2004/07/PartyJuice.DbEntity")]
    [System.SerializableAttribute()]
    public partial class SaleOrder : PartyJuice.PJManagementSystem.PJServiceReference.IdEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PartyJuice.PJManagementSystem.PJServiceReference.Client ClientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PartyJuice.PJManagementSystem.PJServiceReference.WarehouseElement[] ItemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PartyJuice.PJManagementSystem.PJServiceReference.User SellerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double TotalCostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PartyJuice.PJManagementSystem.PJServiceReference.Warehouse WarehouseField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PartyJuice.PJManagementSystem.PJServiceReference.Client Client {
            get {
                return this.ClientField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientField, value) != true)) {
                    this.ClientField = value;
                    this.RaisePropertyChanged("Client");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreationDate {
            get {
                return this.CreationDateField;
            }
            set {
                if ((this.CreationDateField.Equals(value) != true)) {
                    this.CreationDateField = value;
                    this.RaisePropertyChanged("CreationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PartyJuice.PJManagementSystem.PJServiceReference.WarehouseElement[] Items {
            get {
                return this.ItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemsField, value) != true)) {
                    this.ItemsField = value;
                    this.RaisePropertyChanged("Items");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Number {
            get {
                return this.NumberField;
            }
            set {
                if ((object.ReferenceEquals(this.NumberField, value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PartyJuice.PJManagementSystem.PJServiceReference.User Seller {
            get {
                return this.SellerField;
            }
            set {
                if ((object.ReferenceEquals(this.SellerField, value) != true)) {
                    this.SellerField = value;
                    this.RaisePropertyChanged("Seller");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double TotalCost {
            get {
                return this.TotalCostField;
            }
            set {
                if ((this.TotalCostField.Equals(value) != true)) {
                    this.TotalCostField = value;
                    this.RaisePropertyChanged("TotalCost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PartyJuice.PJManagementSystem.PJServiceReference.Warehouse Warehouse {
            get {
                return this.WarehouseField;
            }
            set {
                if ((object.ReferenceEquals(this.WarehouseField, value) != true)) {
                    this.WarehouseField = value;
                    this.RaisePropertyChanged("Warehouse");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/PartyJuice.DbEntity")]
    [System.SerializableAttribute()]
    public partial class User : PartyJuice.PJManagementSystem.PJServiceReference.IdEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PartyJuice.PJManagementSystem.PJServiceReference.Roles RoleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login {
            get {
                return this.LoginField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginField, value) != true)) {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PartyJuice.PJManagementSystem.PJServiceReference.Roles Role {
            get {
                return this.RoleField;
            }
            set {
                if ((this.RoleField.Equals(value) != true)) {
                    this.RoleField = value;
                    this.RaisePropertyChanged("Role");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PurchaseInvoice", Namespace="http://schemas.datacontract.org/2004/07/PartyJuice.DbEntity")]
    [System.SerializableAttribute()]
    public partial class PurchaseInvoice : PartyJuice.PJManagementSystem.PJServiceReference.IdEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PartyJuice.PJManagementSystem.PJServiceReference.WarehouseElement[] ItemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PartyJuice.PJManagementSystem.PJServiceReference.User StoreKeeperField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PartyJuice.PJManagementSystem.PJServiceReference.Warehouse WarehouseField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreationDate {
            get {
                return this.CreationDateField;
            }
            set {
                if ((this.CreationDateField.Equals(value) != true)) {
                    this.CreationDateField = value;
                    this.RaisePropertyChanged("CreationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PartyJuice.PJManagementSystem.PJServiceReference.WarehouseElement[] Items {
            get {
                return this.ItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemsField, value) != true)) {
                    this.ItemsField = value;
                    this.RaisePropertyChanged("Items");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Number {
            get {
                return this.NumberField;
            }
            set {
                if ((object.ReferenceEquals(this.NumberField, value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PartyJuice.PJManagementSystem.PJServiceReference.User StoreKeeper {
            get {
                return this.StoreKeeperField;
            }
            set {
                if ((object.ReferenceEquals(this.StoreKeeperField, value) != true)) {
                    this.StoreKeeperField = value;
                    this.RaisePropertyChanged("StoreKeeper");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PartyJuice.PJManagementSystem.PJServiceReference.Warehouse Warehouse {
            get {
                return this.WarehouseField;
            }
            set {
                if ((object.ReferenceEquals(this.WarehouseField, value) != true)) {
                    this.WarehouseField = value;
                    this.RaisePropertyChanged("Warehouse");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NameEntity", Namespace="http://schemas.datacontract.org/2004/07/PartyJuice.DbEntity")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PartyJuice.PJManagementSystem.PJServiceReference.Drink))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PartyJuice.PJManagementSystem.PJServiceReference.DrinkType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PartyJuice.PJManagementSystem.PJServiceReference.Producer))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PartyJuice.PJManagementSystem.PJServiceReference.Address))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PartyJuice.PJManagementSystem.PJServiceReference.Warehouse))]
    public partial class NameEntity : PartyJuice.PJManagementSystem.PJServiceReference.IdEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Drink", Namespace="http://schemas.datacontract.org/2004/07/PartyJuice.DbEntity")]
    [System.SerializableAttribute()]
    public partial class Drink : PartyJuice.PJManagementSystem.PJServiceReference.NameEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PartyJuice.PJManagementSystem.PJServiceReference.DrinkType DrinkTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PartyJuice.PJManagementSystem.PJServiceReference.Price PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PartyJuice.PJManagementSystem.PJServiceReference.Producer ProducerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double VolumeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PartyJuice.PJManagementSystem.PJServiceReference.DrinkType DrinkType {
            get {
                return this.DrinkTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.DrinkTypeField, value) != true)) {
                    this.DrinkTypeField = value;
                    this.RaisePropertyChanged("DrinkType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PartyJuice.PJManagementSystem.PJServiceReference.Price Price {
            get {
                return this.PriceField;
            }
            set {
                if ((object.ReferenceEquals(this.PriceField, value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PartyJuice.PJManagementSystem.PJServiceReference.Producer Producer {
            get {
                return this.ProducerField;
            }
            set {
                if ((object.ReferenceEquals(this.ProducerField, value) != true)) {
                    this.ProducerField = value;
                    this.RaisePropertyChanged("Producer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Volume {
            get {
                return this.VolumeField;
            }
            set {
                if ((this.VolumeField.Equals(value) != true)) {
                    this.VolumeField = value;
                    this.RaisePropertyChanged("Volume");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DrinkType", Namespace="http://schemas.datacontract.org/2004/07/PartyJuice.DbEntity")]
    [System.SerializableAttribute()]
    public partial class DrinkType : PartyJuice.PJManagementSystem.PJServiceReference.NameEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PartyJuice.PJManagementSystem.PJServiceReference.DrinkType ParentDrinkTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PartyJuice.PJManagementSystem.PJServiceReference.DrinkType ParentDrinkType {
            get {
                return this.ParentDrinkTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ParentDrinkTypeField, value) != true)) {
                    this.ParentDrinkTypeField = value;
                    this.RaisePropertyChanged("ParentDrinkType");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Producer", Namespace="http://schemas.datacontract.org/2004/07/PartyJuice.DbEntity")]
    [System.SerializableAttribute()]
    public partial class Producer : PartyJuice.PJManagementSystem.PJServiceReference.NameEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PartyJuice.PJManagementSystem.PJServiceReference.Address AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PartyJuice.PJManagementSystem.PJServiceReference.PhoneNumber[] PhoneNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PartyJuice.PJManagementSystem.PJServiceReference.Address Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PartyJuice.PJManagementSystem.PJServiceReference.PhoneNumber[] PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Address", Namespace="http://schemas.datacontract.org/2004/07/PartyJuice.DbEntity")]
    [System.SerializableAttribute()]
    public partial class Address : PartyJuice.PJManagementSystem.PJServiceReference.NameEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PartyJuice.PJManagementSystem.PJServiceReference.Countries CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TownField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PartyJuice.PJManagementSystem.PJServiceReference.Countries Country {
            get {
                return this.CountryField;
            }
            set {
                if ((this.CountryField.Equals(value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Number {
            get {
                return this.NumberField;
            }
            set {
                if ((object.ReferenceEquals(this.NumberField, value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Town {
            get {
                return this.TownField;
            }
            set {
                if ((object.ReferenceEquals(this.TownField, value) != true)) {
                    this.TownField = value;
                    this.RaisePropertyChanged("Town");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Countries", Namespace="http://schemas.datacontract.org/2004/07/PartyJuice.DbEntity.Enums")]
    public enum Countries : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        England = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        USA = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        France = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ukraine = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Russia = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Germany = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Brazil = 6,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PhoneNumberKind", Namespace="http://schemas.datacontract.org/2004/07/PartyJuice.DbEntity.Enums")]
    public enum PhoneNumberKind : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Mobile = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Work = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Home = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Office = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sex", Namespace="http://schemas.datacontract.org/2004/07/PartyJuice.DbEntity.Enums")]
    public enum Sex : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Male = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Female = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Roles", Namespace="http://schemas.datacontract.org/2004/07/PartyJuice.DbEntity.Enums")]
    public enum Roles : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Admin = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Manager = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Seller = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        StoreKeeper = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PJServiceReference.IPJService")]
    public interface IPJService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPJService/GetWarehouses", ReplyAction="http://tempuri.org/IPJService/GetWarehousesResponse")]
        PartyJuice.PJManagementSystem.PJServiceReference.Warehouse[] GetWarehouses();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPJService/GetWarehouses", ReplyAction="http://tempuri.org/IPJService/GetWarehousesResponse")]
        System.Threading.Tasks.Task<PartyJuice.PJManagementSystem.PJServiceReference.Warehouse[]> GetWarehousesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPJService/GetDrinksByWarehouseId", ReplyAction="http://tempuri.org/IPJService/GetDrinksByWarehouseIdResponse")]
        PartyJuice.PJManagementSystem.PJServiceReference.Drink[] GetDrinksByWarehouseId(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPJService/GetDrinksByWarehouseId", ReplyAction="http://tempuri.org/IPJService/GetDrinksByWarehouseIdResponse")]
        System.Threading.Tasks.Task<PartyJuice.PJManagementSystem.PJServiceReference.Drink[]> GetDrinksByWarehouseIdAsync(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPJService/GetClients", ReplyAction="http://tempuri.org/IPJService/GetClientsResponse")]
        PartyJuice.PJManagementSystem.PJServiceReference.Client[] GetClients();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPJService/GetClients", ReplyAction="http://tempuri.org/IPJService/GetClientsResponse")]
        System.Threading.Tasks.Task<PartyJuice.PJManagementSystem.PJServiceReference.Client[]> GetClientsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPJService/GetClientsWhoHasBirthday", ReplyAction="http://tempuri.org/IPJService/GetClientsWhoHasBirthdayResponse")]
        PartyJuice.PJManagementSystem.PJServiceReference.Client[] GetClientsWhoHasBirthday(System.DateTime day);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPJService/GetClientsWhoHasBirthday", ReplyAction="http://tempuri.org/IPJService/GetClientsWhoHasBirthdayResponse")]
        System.Threading.Tasks.Task<PartyJuice.PJManagementSystem.PJServiceReference.Client[]> GetClientsWhoHasBirthdayAsync(System.DateTime day);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPJService/GetSaleOrdersByWarehouseId", ReplyAction="http://tempuri.org/IPJService/GetSaleOrdersByWarehouseIdResponse")]
        PartyJuice.PJManagementSystem.PJServiceReference.SaleOrder[] GetSaleOrdersByWarehouseId(System.Guid warehouseId, System.DateTime dateStart);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPJService/GetSaleOrdersByWarehouseId", ReplyAction="http://tempuri.org/IPJService/GetSaleOrdersByWarehouseIdResponse")]
        System.Threading.Tasks.Task<PartyJuice.PJManagementSystem.PJServiceReference.SaleOrder[]> GetSaleOrdersByWarehouseIdAsync(System.Guid warehouseId, System.DateTime dateStart);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPJService/GetSaleOrdersByClientId", ReplyAction="http://tempuri.org/IPJService/GetSaleOrdersByClientIdResponse")]
        PartyJuice.PJManagementSystem.PJServiceReference.SaleOrder[] GetSaleOrdersByClientId(System.Guid clientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPJService/GetSaleOrdersByClientId", ReplyAction="http://tempuri.org/IPJService/GetSaleOrdersByClientIdResponse")]
        System.Threading.Tasks.Task<PartyJuice.PJManagementSystem.PJServiceReference.SaleOrder[]> GetSaleOrdersByClientIdAsync(System.Guid clientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPJService/GetPurchaseInvoicesByWarehouseId", ReplyAction="http://tempuri.org/IPJService/GetPurchaseInvoicesByWarehouseIdResponse")]
        PartyJuice.PJManagementSystem.PJServiceReference.PurchaseInvoice[] GetPurchaseInvoicesByWarehouseId(System.Guid id, System.DateTime dateStart);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPJService/GetPurchaseInvoicesByWarehouseId", ReplyAction="http://tempuri.org/IPJService/GetPurchaseInvoicesByWarehouseIdResponse")]
        System.Threading.Tasks.Task<PartyJuice.PJManagementSystem.PJServiceReference.PurchaseInvoice[]> GetPurchaseInvoicesByWarehouseIdAsync(System.Guid id, System.DateTime dateStart);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPJService/GetPurchaseInvoicesByStoreKeeperId", ReplyAction="http://tempuri.org/IPJService/GetPurchaseInvoicesByStoreKeeperIdResponse")]
        PartyJuice.PJManagementSystem.PJServiceReference.PurchaseInvoice[] GetPurchaseInvoicesByStoreKeeperId(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPJService/GetPurchaseInvoicesByStoreKeeperId", ReplyAction="http://tempuri.org/IPJService/GetPurchaseInvoicesByStoreKeeperIdResponse")]
        System.Threading.Tasks.Task<PartyJuice.PJManagementSystem.PJServiceReference.PurchaseInvoice[]> GetPurchaseInvoicesByStoreKeeperIdAsync(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPJService/GetClientInfo", ReplyAction="http://tempuri.org/IPJService/GetClientInfoResponse")]
        PartyJuice.PJManagementSystem.PJServiceReference.Client GetClientInfo(System.Guid clientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPJService/GetClientInfo", ReplyAction="http://tempuri.org/IPJService/GetClientInfoResponse")]
        System.Threading.Tasks.Task<PartyJuice.PJManagementSystem.PJServiceReference.Client> GetClientInfoAsync(System.Guid clientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPJService/UserValidation", ReplyAction="http://tempuri.org/IPJService/UserValidationResponse")]
        bool UserValidation(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPJService/UserValidation", ReplyAction="http://tempuri.org/IPJService/UserValidationResponse")]
        System.Threading.Tasks.Task<bool> UserValidationAsync(string login, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPJServiceChannel : PartyJuice.PJManagementSystem.PJServiceReference.IPJService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PJServiceClient : System.ServiceModel.ClientBase<PartyJuice.PJManagementSystem.PJServiceReference.IPJService>, PartyJuice.PJManagementSystem.PJServiceReference.IPJService {
        
        public PJServiceClient() {
        }
        
        public PJServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PJServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PJServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PJServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PartyJuice.PJManagementSystem.PJServiceReference.Warehouse[] GetWarehouses() {
            return base.Channel.GetWarehouses();
        }
        
        public System.Threading.Tasks.Task<PartyJuice.PJManagementSystem.PJServiceReference.Warehouse[]> GetWarehousesAsync() {
            return base.Channel.GetWarehousesAsync();
        }
        
        public PartyJuice.PJManagementSystem.PJServiceReference.Drink[] GetDrinksByWarehouseId(System.Guid id) {
            return base.Channel.GetDrinksByWarehouseId(id);
        }
        
        public System.Threading.Tasks.Task<PartyJuice.PJManagementSystem.PJServiceReference.Drink[]> GetDrinksByWarehouseIdAsync(System.Guid id) {
            return base.Channel.GetDrinksByWarehouseIdAsync(id);
        }
        
        public PartyJuice.PJManagementSystem.PJServiceReference.Client[] GetClients() {
            return base.Channel.GetClients();
        }
        
        public System.Threading.Tasks.Task<PartyJuice.PJManagementSystem.PJServiceReference.Client[]> GetClientsAsync() {
            return base.Channel.GetClientsAsync();
        }
        
        public PartyJuice.PJManagementSystem.PJServiceReference.Client[] GetClientsWhoHasBirthday(System.DateTime day) {
            return base.Channel.GetClientsWhoHasBirthday(day);
        }
        
        public System.Threading.Tasks.Task<PartyJuice.PJManagementSystem.PJServiceReference.Client[]> GetClientsWhoHasBirthdayAsync(System.DateTime day) {
            return base.Channel.GetClientsWhoHasBirthdayAsync(day);
        }
        
        public PartyJuice.PJManagementSystem.PJServiceReference.SaleOrder[] GetSaleOrdersByWarehouseId(System.Guid warehouseId, System.DateTime dateStart) {
            return base.Channel.GetSaleOrdersByWarehouseId(warehouseId, dateStart);
        }
        
        public System.Threading.Tasks.Task<PartyJuice.PJManagementSystem.PJServiceReference.SaleOrder[]> GetSaleOrdersByWarehouseIdAsync(System.Guid warehouseId, System.DateTime dateStart) {
            return base.Channel.GetSaleOrdersByWarehouseIdAsync(warehouseId, dateStart);
        }
        
        public PartyJuice.PJManagementSystem.PJServiceReference.SaleOrder[] GetSaleOrdersByClientId(System.Guid clientId) {
            return base.Channel.GetSaleOrdersByClientId(clientId);
        }
        
        public System.Threading.Tasks.Task<PartyJuice.PJManagementSystem.PJServiceReference.SaleOrder[]> GetSaleOrdersByClientIdAsync(System.Guid clientId) {
            return base.Channel.GetSaleOrdersByClientIdAsync(clientId);
        }
        
        public PartyJuice.PJManagementSystem.PJServiceReference.PurchaseInvoice[] GetPurchaseInvoicesByWarehouseId(System.Guid id, System.DateTime dateStart) {
            return base.Channel.GetPurchaseInvoicesByWarehouseId(id, dateStart);
        }
        
        public System.Threading.Tasks.Task<PartyJuice.PJManagementSystem.PJServiceReference.PurchaseInvoice[]> GetPurchaseInvoicesByWarehouseIdAsync(System.Guid id, System.DateTime dateStart) {
            return base.Channel.GetPurchaseInvoicesByWarehouseIdAsync(id, dateStart);
        }
        
        public PartyJuice.PJManagementSystem.PJServiceReference.PurchaseInvoice[] GetPurchaseInvoicesByStoreKeeperId(System.Guid id) {
            return base.Channel.GetPurchaseInvoicesByStoreKeeperId(id);
        }
        
        public System.Threading.Tasks.Task<PartyJuice.PJManagementSystem.PJServiceReference.PurchaseInvoice[]> GetPurchaseInvoicesByStoreKeeperIdAsync(System.Guid id) {
            return base.Channel.GetPurchaseInvoicesByStoreKeeperIdAsync(id);
        }
        
        public PartyJuice.PJManagementSystem.PJServiceReference.Client GetClientInfo(System.Guid clientId) {
            return base.Channel.GetClientInfo(clientId);
        }
        
        public System.Threading.Tasks.Task<PartyJuice.PJManagementSystem.PJServiceReference.Client> GetClientInfoAsync(System.Guid clientId) {
            return base.Channel.GetClientInfoAsync(clientId);
        }
        
        public bool UserValidation(string login, string password) {
            return base.Channel.UserValidation(login, password);
        }
        
        public System.Threading.Tasks.Task<bool> UserValidationAsync(string login, string password) {
            return base.Channel.UserValidationAsync(login, password);
        }
    }
}
